apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeintel

resources:
  - summarizer-configmap.yaml
  - summarizer-secret.yaml
  - summarizer-deployment.yaml
  - summarizer-service.yaml
  - summarizer-hpa.yaml
  - summarizer-pdb.yaml
