apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarizer-api
  namespace: kubeintel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summarizer-api
  template:
    metadata:
      labels:
        app: summarizer-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: summarizer-api
          image: ghcr.io/simranjeet19/kubeintel-summarizer-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: summarizer-config
          env:
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: summarizer-secret
                  key: ANTHROPIC_API_KEY
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
