apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeintel

resources:
  - metrics-server.yaml
  - prometheus-rbac.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
  - grafana-secret.yaml
  - grafana-provisioning.yaml
  - grafana-deployment.yaml
  - observability-networkpolicies.yaml
