apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kubeintel
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      evaluation_interval: 30s

    scrape_configs:
      # scrape prometheus itself
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']

      # scrape summarizer-api /metrics endpoint
      - job_name: summarizer-api
        static_configs:
          - targets: ['summarizer-svc:8000']
        metrics_path: /metrics

      # scrape kubernetes node metrics via metrics-server
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['kubeintel']
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
