apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: kubeintel
spec:
  template:
    spec:
      containers:
        - name: n8n
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
