apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeintel

resources:
  - ../../k8s

patches:
  # prod: run 2 replicas of summarizer-api
  - path: summarizer-replicas-patch.yaml
