apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: n8n-role
  namespace: kubeintel
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["n8n-config"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["n8n-secret"]
    verbs: ["get"]
