apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeintel

resources:
  - n8n-configmap.yaml
  - n8n-secret.yaml
  - n8n-pvc.yaml
  - n8n-deployment.yaml
  - n8n-service.yaml
